"""'addteacher'

Revision ID: 2d0592527dd5
Revises: 70e568207abf
Create Date: 2022-12-31 16:29:26.931677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d0592527dd5'
down_revision = '70e568207abf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('school')

    op.create_table('item',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=33), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('barcode', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('owner', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['user.id'], name='item_owner_fkey'),
    sa.PrimaryKeyConstraint('id', name='item_pkey'),
    sa.UniqueConstraint('barcode', name='item_barcode_key')
    )
    # ### end Alembic commands ###
