"""empty message

Revision ID: 503ac3f97504
Revises: 2d0592527dd5
Create Date: 2022-12-31 17:22:49.211803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '503ac3f97504'
down_revision = '2d0592527dd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('school')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
